### ISSUE TITLE
3. 뉴스앱 적용하기

### ISSUE THREAD

**Issue by jsontype** [jsontype/movieapp-kimjh#26]
1. 메뉴 컴포넌트 만들기
2. App에서, 메뉴 컴포넌트를 렌더링해서 클릭한 것이 Movie면 Movie가 뜨고, News면 News가 뜬다.
3. *** 타입스크립트 적용!!!

**Comment by kjh-busan** [comment]
#25
뉴스앱 버튼토글 형식으로 추가
