### ISSUE TITLE
인풋창 널 체크

### ISSUE THREAD

**Issue by jsontype** [jsontype/movieapp-kimjh#35]
text가 널이고 한번 서밋을 했을 때 -> 인풋창을 빨간 보더 주기
border: 1px solid $color-red;
`* 할일을 입력해주십시오.`

그 뒤 text에 입력을 할 경우 원래 인풋색으로 변경

**Comment by kjh-busan** [comment]
#35 
버튼 클릭시 체크 기능(인풋창 색상 변경, 에러메세지 출력) 추가
